[Travis] codecov with gcc-9

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -59,7 +59,7 @@ matrix:
             - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
               key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
 
-    - env: TOOLSET=gcc TOOLSET_VER=8 STDLIB=libstdc++ STDLIB_VER=8 CODE_COVERAGE=true
+    - env: TOOLSET=gcc TOOLSET_VER=8 STDLIB=libstdc++ STDLIB_VER=8
       addons:
         apt:
           packages:
@@ -67,7 +67,7 @@ matrix:
           sources:
             - sourceline: 'ppa:ubuntu-toolchain-r/test'
 
-    - env: TOOLSET=gcc TOOLSET_VER=9 STDLIB=libstdc++ STDLIB_VER=9
+    - env: TOOLSET=gcc TOOLSET_VER=9 STDLIB=libstdc++ STDLIB_VER=9 CODE_COVERAGE=true
       addons:
         apt:
           packages:
@@ -151,6 +151,7 @@ install:
     ./bootstrap.sh --with-toolset=clang --with-libraries=${BOOST_LIBS}
     sudo ./b2 -d0 -j10 install toolset=clang ${BOOST_BUILD_TYPE} cxxflags="-stdlib=libc++"
   fi
+  cd ${THIRD_PARTY_DIR}
 
 ################################################################################
 # Install the latest CMake
@@ -162,6 +163,18 @@ install:
   mkdir -p ${CMAKE_DIR} && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${CMAKE_DIR}
   export PATH=${CMAKE_DIR}/bin:${PATH}
   cmake --version
+
+################################################################################
+# Install the latest lcov
+################################################################################
+- |
+  if [[ "${CODE_COVERAGE}" == "true" ]]; then
+    sudo apt-get install -y libjson-perl libperlio-gzip-perl
+    git clone https://github.com/linux-test-project/lcov.git
+    LCOV_DIR=${THIRD_PARTY_DIR}/lcov
+    export PATH=${LCOV_DIR}/bin:${PATH}
+    lcov --version
+  fi
 
 ################################################################################
 # Install the dependent GitHub repositories xstd and bit_set
@@ -199,12 +212,13 @@ before_script:
 script:
 - |
   cmake --build . -v
-  ctest -E "search|traversal"
+  ctest
 
 after_success:
 - |
   if [[ "${CODE_COVERAGE}" == "true" ]]; then
-    bash <(curl -s https://codecov.io/bash)
+    lcov --directory . --capture --output-file coverage.info
+    bash <(curl -s https://codecov.io/bash) -v -f coverage.info || echo 'Codecov failed to upload'
   fi
 
 notifications:
